Vagrant.configure("2") do |config|
    config.vm.box = "local/hashistack"
    config.vm.network "private_network", ip: "10.0.3.10"
    config.vm.box_url = "file://../packer/output-hashistack/package.box"

    config.vm.provision "ansible_local" do |startup|
        run = "always"
        startup.playbook = "/etc/ansible/startup.yml"
    end
    config.vm.provision "ansible_local" do |ansible|
        ansible.provisioning_path = "/vagrant/ansible"
        ansible.playbook = "playbook.yml"
    end
end
