Vagrant.configure("2") do |config|
    config.vm.box = "local/hashistack"
    # Working directory is `[project-root]/template/test` will pick box built locally in order to run test
    config.vm.box_url = "file://../../packer/output-hashistack/package.box"

    config.vm.provision "ansible_local" do |ansible|
        ansible.provisioning_path = "/vagrant/ansible"
        ansible.playbook = "playbook.yml"
    end
end
