Vagrant.configure("2") do |config|
    config.vm.box = "fredrikhgrelland/hashistack"
    config.vm.provider "virtualbox" do |vb|
        vb.linked_clone = true
        vb.memory = 2048
    end
    config.vm.provision "ansible_local" do |ansible|
        ansible.provisioning_path = "/vagrant/ansible"
        ansible.playbook = "playbook.yml" # Note this playbook is, in this context, /ansible/playbook.yml
    end
end
