Vagrant.configure("2") do |config|
    config.vm.box = "local/hashistack"
    # Working directory is `[project-root]/template/test` will pick box built locally in order to run test
    config.vm.box_url = "file://../../packer/output-hashistack/package.box"
    config.vm.synced_folder "./template_example", "/vagrant"

    # Sync the root folder to /box so we can rewire to use local files instead of packaged ones.
    config.vm.synced_folder "../", "/box"

    #Do not use linked clone for development
    config.vm.provider "virtualbox" do |v|
      v.linked_clone = false
    end

    config.vm.provision "ansible_local" do |ansible|
        ansible.provisioning_path = "/vagrant/dev/ansible"
        ansible.playbook = "playbook.yml" # Note this playbook is, in this context, /template/test/ansible/playbook.yml
    end
end