Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.box_version = "1.0.282"

  # Hashicorp consul ui
  config.vm.network "forwarded_port", guest: 8500, host: 8500, host_ip: "127.0.0.1"

  # Hashicorp nomad ui
  config.vm.network "forwarded_port", guest: 4646, host: 4646

  config.vm.provision "ansible_local" do |ansible|
    ansible.install_mode = "pip"
    ansible.pip_install_cmd = "sudo apt-get install python3-distutils -y && curl -k -s https://bootstrap.pypa.io/get-pip.py | sudo python3"
    ansible.playbook = "playbook.yml"
    ansible.provisioning_path = "/vagrant/ansible"
  end
end
