Vagrant.configure("2") do |config|
    config.vm.box = "fredrikhgrelland/hashistack"
    config.vm.network "private_network", ip: "10.0.3.10"

    # Hashicorp consul ui
    config.vm.network "forwarded_port", guest: 8500, host: 8500, host_ip: "127.0.0.1"
    # Hashicorp nomad ui
    config.vm.network "forwarded_port", guest: 4646, host: 4646, host_ip: "127.0.0.1"
    # Hashicorp vault ui
    config.vm.network "forwarded_port", guest: 8200, host: 8200, host_ip: "127.0.0.1"

    config.vm.provider "virtualbox" do |vb|
        vb.linked_clone = true
        vb.memory = 2048
    end
    config.vm.provision "shell", inline: "cp /vagrant/vagrant/conf/hashistack/consul/99-override.hcl /etc/consul.d/99-override.hcl || true"
    config.vm.provision "shell", inline: "cp /vagrant/vagrant/conf/hashistack/vault/99-override.hcl /etc/vault.d/99-override.hcl || true"
    config.vm.provision "shell", inline: "cp /vagrant/vagrant/conf/hashistack/nomad/99-override.hcl /etc/nomad.d/99-override.hcl || true"
    config.vm.provision "ansible_local" do |startup|
        run = "always"
        startup.playbook = "/etc/ansible/bootstrap.yml"
    end
end
