Vagrant.configure("2") do |config|
    config.vm.box = "fredrikhgrelland/hashistack"
    config.vm.network "private_network", ip: "10.0.3.10"

    # Hashicorp consul ui
    config.vm.network "forwarded_port", guest: 8500, host: 8500, host_ip: "127.0.0.1", auto_correct: true
    # Hashicorp nomad ui
    config.vm.network "forwarded_port", guest: 4646, host: 4646, host_ip: "127.0.0.1", auto_correct: true
    # Hashicorp vault ui
    config.vm.network "forwarded_port", guest: 8200, host: 8200, host_ip: "127.0.0.1", auto_correct: true

    config.vm.provider "virtualbox" do |vb|
        vb.linked_clone = true
        vb.memory = 2048
    end
    config.vm.provision "shell", args: ["/vagrant/dev/vagrant/bootstrap/pre_ansible.sh"], inline: "if [ -f \"$1\" ]; then . $1; else echo You may add $1 if you want something to happen here; fi"
    config.vm.provision "ansible_local" do |startup|
        run = "always"
        startup.playbook = "/etc/ansible/bootstrap.yml"
        startup.raw_arguments = Shellwords.shellsplit(ENV["ANSIBLE_ARGS"]) if ENV["ANSIBLE_ARGS"]
    end
    config.vm.provision "shell", args: ["/vagrant/dev/vagrant/bootstrap/post_ansible.sh"], inline: "if [ -f \"$1\" ]; then . $1; else echo You may add $1 if you want something to happen here; fi"
end
