name: CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run vagrant box with tests
        run: make test