---
- hosts: all
  become: yes
  vars:
    daemons:
      - vault
      - consul
      - nomad
  tasks:
    - name: "Verify default env variables"
      set_fact:
        var_consul_acl: "{{ lookup('env', 'VAR_CONSUL_ACL') | default('allow', true) }}"
        var_environment: "{{ lookup('env', 'VAR_ENVIRONMENT') | default('dev', true) }}"
      register: env_defaults
    - debug: msg="env_defaults are {{ env_defaults }}"

    - name: "Start hashistack"
      systemd: name={{item}} state=started
      loop: "{{ daemons }}"

    - name: Wait for consul to start
      uri:
        url: http://127.0.0.1:8500/ui/dc1/services
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1

    - name: Wait for nomad to start
      uri:
        url: http://127.0.0.1:4646/v1/jobs
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1

    - name: Wait for vault to start
      uri:
        url: http://127.0.0.1:8200/ui/
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1